### ISSUE TITLE
Batch issuance

### ISSUE THREAD

**Issue by callumdmay** [jedisct1/blind-rsa-signatures#1]
Hi there,

Has there been any consideration into making an API surface that allows signing multiple message with the same context and client secret?

**Comment by jedisct1** [comment]
Due to the blinding factor, every message representative the signer gets is indistinguishable from a random element. This is actually the whole point of blind signatures :)

Functions to blind and sign a batch of messages can be added, but there wouldn't be any performance benefits by doing so. All a batch signature function would do is loop over the inputs to sign them individually.

Something that's better done at application-level, especially since it can then take advantage of whatever system you already have to spread the signatures across multiple CPU cores.

**Comment by callumdmay** [comment]
It would be easier to use the same client secret for each issuance flow, but I understand your hesitation
